# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import battleships_pb2 as battleships__pb2


class BattleshipsStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Game = channel.stream_stream(
                '/battleships.Battleships/Game',
                request_serializer=battleships__pb2.Request.SerializeToString,
                response_deserializer=battleships__pb2.Response.FromString,
                )


class BattleshipsServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Game(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BattleshipsServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Game': grpc.stream_stream_rpc_method_handler(
                    servicer.Game,
                    request_deserializer=battleships__pb2.Request.FromString,
                    response_serializer=battleships__pb2.Response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'battleships.Battleships', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Battleships(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Game(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/battleships.Battleships/Game',
            battleships__pb2.Request.SerializeToString,
            battleships__pb2.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
