# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: battleships.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='battleships.proto',
  package='battleships',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x11\x62\x61ttleships.proto\x12\x0b\x62\x61ttleships\"\xa1\x01\n\x07Request\x12+\n\x04join\x18\x01 \x01(\x0b\x32\x1b.battleships.Request.PlayerH\x00\x12#\n\x04move\x18\x02 \x01(\x0b\x32\x13.battleships.AttackH\x00\x12%\n\x06report\x18\x03 \x01(\x0b\x32\x13.battleships.StatusH\x00\x1a\x14\n\x06Player\x12\n\n\x02id\x18\x01 \x01(\tB\x07\n\x05\x65vent\"\xd2\x01\n\x08Response\x12+\n\x04turn\x18\x01 \x01(\x0e\x32\x1b.battleships.Response.StateH\x00\x12#\n\x04move\x18\x02 \x01(\x0b\x32\x13.battleships.AttackH\x00\x12%\n\x06report\x18\x03 \x01(\x0b\x32\x13.battleships.StatusH\x00\"D\n\x05State\x12\t\n\x05\x42\x45GIN\x10\x00\x12\x0e\n\nSTART_TURN\x10\x01\x12\r\n\tSTOP_TURN\x10\x02\x12\x07\n\x03WIN\x10\x03\x12\x08\n\x04LOSE\x10\x04\x42\x07\n\x05\x65vent\"\x18\n\x06\x41ttack\x12\x0e\n\x06vector\x18\x01 \x01(\t\"Z\n\x06Status\x12(\n\x05state\x18\x01 \x01(\x0e\x32\x19.battleships.Status.State\"&\n\x05State\x12\x08\n\x04MISS\x10\x00\x12\x07\n\x03HIT\x10\x01\x12\n\n\x06\x44\x45\x46\x45\x41T\x10\x02\x32H\n\x0b\x42\x61ttleships\x12\x39\n\x04Game\x12\x14.battleships.Request\x1a\x15.battleships.Response\"\x00(\x01\x30\x01\x62\x06proto3'
)



_RESPONSE_STATE = _descriptor.EnumDescriptor(
  name='State',
  full_name='battleships.Response.State',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='BEGIN', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='START_TURN', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='STOP_TURN', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='WIN', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='LOSE', index=4, number=4,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=332,
  serialized_end=400,
)
_sym_db.RegisterEnumDescriptor(_RESPONSE_STATE)

_STATUS_STATE = _descriptor.EnumDescriptor(
  name='State',
  full_name='battleships.Status.State',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='MISS', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='HIT', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='DEFEAT', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=489,
  serialized_end=527,
)
_sym_db.RegisterEnumDescriptor(_STATUS_STATE)


_REQUEST_PLAYER = _descriptor.Descriptor(
  name='Player',
  full_name='battleships.Request.Player',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='battleships.Request.Player.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=167,
  serialized_end=187,
)

_REQUEST = _descriptor.Descriptor(
  name='Request',
  full_name='battleships.Request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='join', full_name='battleships.Request.join', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='move', full_name='battleships.Request.move', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='report', full_name='battleships.Request.report', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_REQUEST_PLAYER, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='event', full_name='battleships.Request.event',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=35,
  serialized_end=196,
)


_RESPONSE = _descriptor.Descriptor(
  name='Response',
  full_name='battleships.Response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='turn', full_name='battleships.Response.turn', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='move', full_name='battleships.Response.move', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='report', full_name='battleships.Response.report', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _RESPONSE_STATE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='event', full_name='battleships.Response.event',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=199,
  serialized_end=409,
)


_ATTACK = _descriptor.Descriptor(
  name='Attack',
  full_name='battleships.Attack',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='vector', full_name='battleships.Attack.vector', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=411,
  serialized_end=435,
)


_STATUS = _descriptor.Descriptor(
  name='Status',
  full_name='battleships.Status',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='state', full_name='battleships.Status.state', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _STATUS_STATE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=437,
  serialized_end=527,
)

_REQUEST_PLAYER.containing_type = _REQUEST
_REQUEST.fields_by_name['join'].message_type = _REQUEST_PLAYER
_REQUEST.fields_by_name['move'].message_type = _ATTACK
_REQUEST.fields_by_name['report'].message_type = _STATUS
_REQUEST.oneofs_by_name['event'].fields.append(
  _REQUEST.fields_by_name['join'])
_REQUEST.fields_by_name['join'].containing_oneof = _REQUEST.oneofs_by_name['event']
_REQUEST.oneofs_by_name['event'].fields.append(
  _REQUEST.fields_by_name['move'])
_REQUEST.fields_by_name['move'].containing_oneof = _REQUEST.oneofs_by_name['event']
_REQUEST.oneofs_by_name['event'].fields.append(
  _REQUEST.fields_by_name['report'])
_REQUEST.fields_by_name['report'].containing_oneof = _REQUEST.oneofs_by_name['event']
_RESPONSE.fields_by_name['turn'].enum_type = _RESPONSE_STATE
_RESPONSE.fields_by_name['move'].message_type = _ATTACK
_RESPONSE.fields_by_name['report'].message_type = _STATUS
_RESPONSE_STATE.containing_type = _RESPONSE
_RESPONSE.oneofs_by_name['event'].fields.append(
  _RESPONSE.fields_by_name['turn'])
_RESPONSE.fields_by_name['turn'].containing_oneof = _RESPONSE.oneofs_by_name['event']
_RESPONSE.oneofs_by_name['event'].fields.append(
  _RESPONSE.fields_by_name['move'])
_RESPONSE.fields_by_name['move'].containing_oneof = _RESPONSE.oneofs_by_name['event']
_RESPONSE.oneofs_by_name['event'].fields.append(
  _RESPONSE.fields_by_name['report'])
_RESPONSE.fields_by_name['report'].containing_oneof = _RESPONSE.oneofs_by_name['event']
_STATUS.fields_by_name['state'].enum_type = _STATUS_STATE
_STATUS_STATE.containing_type = _STATUS
DESCRIPTOR.message_types_by_name['Request'] = _REQUEST
DESCRIPTOR.message_types_by_name['Response'] = _RESPONSE
DESCRIPTOR.message_types_by_name['Attack'] = _ATTACK
DESCRIPTOR.message_types_by_name['Status'] = _STATUS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Request = _reflection.GeneratedProtocolMessageType('Request', (_message.Message,), {

  'Player' : _reflection.GeneratedProtocolMessageType('Player', (_message.Message,), {
    'DESCRIPTOR' : _REQUEST_PLAYER,
    '__module__' : 'battleships_pb2'
    # @@protoc_insertion_point(class_scope:battleships.Request.Player)
    })
  ,
  'DESCRIPTOR' : _REQUEST,
  '__module__' : 'battleships_pb2'
  # @@protoc_insertion_point(class_scope:battleships.Request)
  })
_sym_db.RegisterMessage(Request)
_sym_db.RegisterMessage(Request.Player)

Response = _reflection.GeneratedProtocolMessageType('Response', (_message.Message,), {
  'DESCRIPTOR' : _RESPONSE,
  '__module__' : 'battleships_pb2'
  # @@protoc_insertion_point(class_scope:battleships.Response)
  })
_sym_db.RegisterMessage(Response)

Attack = _reflection.GeneratedProtocolMessageType('Attack', (_message.Message,), {
  'DESCRIPTOR' : _ATTACK,
  '__module__' : 'battleships_pb2'
  # @@protoc_insertion_point(class_scope:battleships.Attack)
  })
_sym_db.RegisterMessage(Attack)

Status = _reflection.GeneratedProtocolMessageType('Status', (_message.Message,), {
  'DESCRIPTOR' : _STATUS,
  '__module__' : 'battleships_pb2'
  # @@protoc_insertion_point(class_scope:battleships.Status)
  })
_sym_db.RegisterMessage(Status)



_BATTLESHIPS = _descriptor.ServiceDescriptor(
  name='Battleships',
  full_name='battleships.Battleships',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=529,
  serialized_end=601,
  methods=[
  _descriptor.MethodDescriptor(
    name='Game',
    full_name='battleships.Battleships.Game',
    index=0,
    containing_service=None,
    input_type=_REQUEST,
    output_type=_RESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_BATTLESHIPS)

DESCRIPTOR.services_by_name['Battleships'] = _BATTLESHIPS

# @@protoc_insertion_point(module_scope)
